### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by CJ666-njust** [mapooon/PetFace#1]
Nice Work! And I have filled in the form to use the PetFace dataset. When will I get this dataset ? Thank you for your time and look forward to your response!

**Comment by mapooon** [comment]
Thank you for your interest in our work.
We sent you the link for the dataset.

**Comment by sssssshf** [comment]
> Thank you for your interest in our work. We sent you the link for the dataset.

有没有百度网盘的数据集连接啊 请问
