### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by jveitchmichaelis** [mapooon/PetFace#4]
Hi, 

We're interested in evaluating the pre-trained models on some new data. Please could you provide more specific information about the development environment? I've tried installing the pinned packages (`requirements.txt`) with versions of Python back to 3.6 and I've run into dependency conflicts or unavailable packages.

For example:

Python 3.6 - fails because `datasets==2.8.0` is unavailable
Python 3.7 - fails because `matplotlib==3.7.2` is unavailable
Python 3.8 and greater - the specified version of torch is unavailable

Thanks!

**Comment by mapooon** [comment]
Thank you for your interest in our work!
We updated the installation instruction with Docker in `README.md`. 
Please try this one.
